/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Clock } from 'three'
import { useFrame } from '@react-three/fiber'

export function Ethereum(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ethereum.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(() => {
    console.log(actions);
    actions.anime.play();
  });

  const delta =new Clock
  useFrame((clicked,delta)=>{
    group.current.rotation.y+=delta*0.5
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, -1.49]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} skeleton={nodes.Alpha_Joints.skeleton} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials.Alpha_Body_MAT} skeleton={nodes.Alpha_Surface.skeleton} />
        </group>
        <mesh name="Curve003" geometry={nodes.Curve003.geometry} material={materials['SVGMat.002']} position={[0, 0, -1.49]} />
        <mesh name="Curve004" geometry={nodes.Curve004.geometry} material={materials['SVGMat.003']} position={[0, 0, -1.49]} />
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['SVGMat.009']} position={[-0.14, 1.46, -1.37]} rotation={[1.61, 0.03, -0.01]} scale={2.25}>
          <mesh name="Curve001_1" geometry={nodes.Curve001_1.geometry} material={materials['SVGMat.008']} />
          <mesh name="Curve009" geometry={nodes.Curve009.geometry} material={materials['SVGMat.010']} />
          <mesh name="Curve010" geometry={nodes.Curve010.geometry} material={materials['SVGMat.011']} />
          <mesh name="Curve011" geometry={nodes.Curve011.geometry} material={materials['SVGMat.012']} />
          <mesh name="Curve012_1" geometry={nodes.Curve012_1.geometry} material={materials['SVGMat.013']} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/ethereum.gltf')
