/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/react.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, -1.49]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} skeleton={nodes.Alpha_Joints.skeleton} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials.Alpha_Body_MAT} skeleton={nodes.Alpha_Surface.skeleton} />
        </group>
        <mesh name="Curve003" geometry={nodes.Curve003.geometry} material={materials['SVGMat.002']} position={[0, 0, -1.49]} />
        <mesh name="Curve004" geometry={nodes.Curve004.geometry} material={materials['SVGMat.003']} position={[0, 0, -1.49]} />
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['SVGMat.006']} position={[0.05, 1.71, -1.4]} rotation={[1.61, 0.01, -0.02]} scale={-2.88} />
      </group>
    </group>
  )
}

useGLTF.preload('/react.gltf')
